services :
  ai-interview:
    build:
      context: ./AiInterview
      dockerfile: Dockerfile
    container_name: ai-interview
    volumes:
    - ./AiInterview:/app
    ports:
    - "8010:8010"
    networks :
    - template



networks:
  template:
    driver: bridge
